services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: workroom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - workroom_pg:/var/lib/postgresql/data

volumes:
  workroom_pg:
